### ISSUE TITLE
电脑运行出错

### ISSUE THREAD

**Issue by hackmgrm** [wpc2333/AutoWatch#1]
ReferenceError: "i" is not defined. ([remote]main.js#412)
ReferenceError: "i" is not defined.
    at main ([remote]main.js:412:0)
    at [remote]main.js:425:0

**Comment by wpc2333** [comment]
> ReferenceError: "i" is not defined. ([remote]main.js#412)
> ReferenceError: "i" is not defined.
> at main ([remote]main.js:412:0)
> at [remote]main.js:425:0

已经解决这个问题，但程序是两年前的版本，大概率已经无法正常运行了
